apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    k3s.io/hostname: hp-mini
  containers:
    - name: docker
      image: docker:19.03.5
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /root/.docker
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: docker-daemon
      image: docker:19.03.5-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
    - name: kubectl
      image: bitnami/kubectl
      command:
        - sleep
      args:
        - 99d
  volumes:
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: regcred
              items:
                - key: .dockerconfigjson
                  path: config.json
