---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rpi-node-cm
  labels:
    app: rpi-node-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpi-node-cm
  template:
    metadata:
      labels:
        app: rpi-node-cm
    spec:
      nodeSelector:
        k3s.io/hostname: pi4-node2
      containers:
        - name: rpi-node-cm
          image: docker.io/vikaspogu/rpi-node-cm:latest
          env:
            - name: user
              valueFrom:
                secretKeyRef:
                  name: userinfo
                  key: user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: userinfo
                  key: password
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: web
              containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 600m
            requests:
              cpu: 500m
              memory: 500m
          volumeMounts:
            - mountPath: /dev/video0
              name: dev-snd
          securityContext:
            privileged: true
      volumes:
        - name: dev-snd
          hostPath:
            path: /dev/video0
---
apiVersion: v1
kind: Service
metadata:
  name: rpi-node-cm-web-ui
spec:
  selector:
    app: rpi-node-cm
  ports:
    - name: admin
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rpi-node-cm-web-ui
spec:
  rules:
    - host: rpi-cm.homenet.vikaspogu.com
      http:
        paths:
          - path: /
            backend:
              serviceName: rpi-node-cm-web-ui
              servicePort: admin
